const { Review } = require('../models');

const reviewData = [
  {
    text: 'Great time and but shy',
    score: 4,
    user_id: 3,
    reviewee_id: 4,
  },
  {
    text: 'Could have been better',
    score: 3,
    user_id: 2,
    reviewee_id: 1,
  },
  {
    text: 'Absolute blast great person',
    score: 5,
    user_id: 4,
    reviewee_id: 2,
  },
  {
    text: 'Horrible human',
    score: 1,
    user_id: 1,
    reviewee_id: 5,
  },
  {
    text: 'Would definitly do it again',
    score: 4,
    user_id: 5,
    reviewee_id: 3,
  },
  {
    text: 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique',
    score: 3,
    user_id: 2,
    reviewee_id: 3,
  },
  {
    text: 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat',
    score: 4,
    user_id: 2,
    reviewee_id: 6,
  },
  {
    text: 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in',
    score: 5,
    user_id: 4,
    reviewee_id: 5,
  },
  {
    text: 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a',
    score: 3,
    user_id: 5,
    reviewee_id: 1,
  },
  {
    text: 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est',
    score: 2,
    user_id: 2,
    reviewee_id: 4,
  },
  {
    text: 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum',
    score: 4,
    user_id: 6,
    reviewee_id: 1,
  },
  {
    text: 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus',
    score: 3,
    user_id: 5,
    reviewee_id: 5,
  },
  {
    text: 'non mi integer ac neque duis bibendum morbi non quam',
    score: 5,
    user_id: 6,
    reviewee_id: 4,
  },
  {
    text: 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula',
    score: 1,
    user_id: 5,
    reviewee_id: 6,
  },
  {
    text: 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus',
    score: 2,
    user_id: 6,
    reviewee_id: 6,
  },
  {
    text: 'maecenas tristique est et tempus semper est quam pharetra magna',
    score: 2,
    user_id: 3,
    reviewee_id: 3,
  },
  {
    text: 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit',
    score: 3,
    user_id: 5,
    reviewee_id: 2,
  },
  {
    text: 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu',
    score: 4,
    user_id: 4,
    reviewee_id: 5,
  },
  {
    text: 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante',
    score: 3,
    user_id: 2,
    reviewee_id: 5,
  },
  {
    text: 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin',
    score: 4,
    user_id: 1,
    reviewee_id: 5,
  },
  {
    text: 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl',
    score: 3,
    user_id: 6,
    reviewee_id: 4,
  },
  {
    text: 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit',
    score: 4,
    user_id: 6,
    reviewee_id: 3,
  },
  {
    text: 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc',
    score: 5,
    user_id: 2,
    reviewee_id: 1,
  },
  {
    text: 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula',
    score: 5,
    user_id: 1,
    reviewee_id: 4,
  },
  {
    text: 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam',
    score: 5,
    user_id: 1,
    reviewee_id: 3,
  },
  {
    text: 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes',
    score: 4,
    user_id: 4,
    reviewee_id: 2,
  },
  {
    text: 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed',
    score: 1,
    user_id: 6,
    reviewee_id: 3,
  },
  {
    text: 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt',
    score: 3,
    user_id: 4,
    reviewee_id: 6,
  },
  {
    text: 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla',
    score: 1,
    user_id: 1,
    reviewee_id: 2,
  },
  {
    text: 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst',
    score: 3,
    user_id: 6,
    reviewee_id: 3,
  },
  {
    text: 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu',
    score: 3,
    user_id: 5,
    reviewee_id: 5,
  },
  {
    text: 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat',
    score: 3,
    user_id: 6,
    reviewee_id: 5,
  },
  {
    text: 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam',
    score: 1,
    user_id: 1,
    reviewee_id: 1,
  },
  {
    text: 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede',
    score: 3,
    user_id: 1,
    reviewee_id: 5,
  },
  {
    text: 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper',
    score: 5,
    user_id: 6,
    reviewee_id: 1,
  },
  {
    text: 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros',
    score: 4,
    user_id: 1,
    reviewee_id: 6,
  },
  {
    text: 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis',
    score: 5,
    user_id: 2,
    reviewee_id: 4,
  },
  {
    text: 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem',
    score: 2,
    user_id: 5,
    reviewee_id: 4,
  },
  {
    text: 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus',
    score: 5,
    user_id: 4,
    reviewee_id: 3,
  },
  {
    text: 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis',
    score: 4,
    user_id: 3,
    reviewee_id: 4,
  },
  {
    text: 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec',
    score: 4,
    user_id: 2,
    reviewee_id: 1,
  },
  {
    text: 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo',
    score: 3,
    user_id: 1,
    reviewee_id: 6,
  },
  {
    text: 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium',
    score: 5,
    user_id: 5,
    reviewee_id: 3,
  },
  {
    text: 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in',
    score: 1,
    user_id: 5,
    reviewee_id: 1,
  },
  {
    text: 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur',
    score: 5,
    user_id: 2,
    reviewee_id: 6,
  },
  {
    text: 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus',
    score: 2,
    user_id: 2,
    reviewee_id: 2,
  },
  {
    text: 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet',
    score: 5,
    user_id: 5,
    reviewee_id: 6,
  },
  {
    text: 'in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti',
    score: 3,
    user_id: 3,
    reviewee_id: 3,
  },
  {
    text: 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus',
    score: 4,
    user_id: 6,
    reviewee_id: 6,
  },
  {
    text: 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum',
    score: 2,
    user_id: 5,
    reviewee_id: 1,
  },
  {
    text: 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis',
    score: 1,
    user_id: 4,
    reviewee_id: 6,
  },
  {
    text: 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed',
    score: 3,
    user_id: 1,
    reviewee_id: 4,
  },
  {
    text: 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus',
    score: 1,
    user_id: 6,
    reviewee_id: 5,
  },
  {
    text: 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus',
    score: 5,
    user_id: 2,
    reviewee_id: 3,
  },
  {
    text: 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel',
    score: 3,
    user_id: 5,
    reviewee_id: 1,
  },
  {
    text: 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',
    score: 3,
    user_id: 3,
    reviewee_id: 3,
  },
  {
    text: 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet',
    score: 2,
    user_id: 1,
    reviewee_id: 6,
  },
  {
    text: 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer',
    score: 1,
    user_id: 5,
    reviewee_id: 3,
  },
  {
    text: 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin',
    score: 5,
    user_id: 3,
    reviewee_id: 1,
  },
  {
    text: 'ipsum aliquam non mauris morbi non lectus aliquam sit amet',
    score: 3,
    user_id: 3,
    reviewee_id: 3,
  },
  {
    text: 'aliquam non mauris morbi non lectus aliquam sit amet diam',
    score: 4,
    user_id: 3,
    reviewee_id: 1,
  },
  {
    text: 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi',
    score: 3,
    user_id: 4,
    reviewee_id: 1,
  },
  {
    text: 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus',
    score: 3,
    user_id: 4,
    reviewee_id: 6,
  },
  {
    text: 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt',
    score: 2,
    user_id: 3,
    reviewee_id: 5,
  },
  {
    text: 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra',
    score: 4,
    user_id: 5,
    reviewee_id: 4,
  },
  {
    text: 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel',
    score: 5,
    user_id: 3,
    reviewee_id: 3,
  },
  {
    text: 'vestibulum sed magna at nunc commodo placerat praesent blandit nam',
    score: 3,
    user_id: 2,
    reviewee_id: 4,
  },
  {
    text: 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi',
    score: 2,
    user_id: 5,
    reviewee_id: 5,
  },
  {
    text: 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue',
    score: 3,
    user_id: 6,
    reviewee_id: 6,
  },
  {
    text: 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum',
    score: 4,
    user_id: 4,
    reviewee_id: 1,
  },
  {
    text: 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus',
    score: 5,
    user_id: 2,
    reviewee_id: 4,
  },
  {
    text: 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique',
    score: 1,
    user_id: 1,
    reviewee_id: 6,
  },
  {
    text: 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam',
    score: 5,
    user_id: 1,
    reviewee_id: 5,
  },
  {
    text: 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac',
    score: 2,
    user_id: 1,
    reviewee_id: 4,
  },
  {
    text: 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum',
    score: 5,
    user_id: 1,
    reviewee_id: 3,
  },
  {
    text: 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat',
    score: 2,
    user_id: 6,
    reviewee_id: 1,
  },
  {
    text: 'arcu sed augue aliquam erat volutpat in congue etiam justo',
    score: 2,
    user_id: 4,
    reviewee_id: 4,
  },
  {
    text: 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh',
    score: 4,
    user_id: 1,
    reviewee_id: 4,
  },
  {
    text: 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices',
    score: 3,
    user_id: 6,
    reviewee_id: 4,
  },
  {
    text: 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien',
    score: 1,
    user_id: 6,
    reviewee_id: 2,
  },
  {
    text: 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi',
    score: 5,
    user_id: 5,
    reviewee_id: 4,
  },
  {
    text: 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla',
    score: 4,
    user_id: 3,
    reviewee_id: 6,
  },
  {
    text: 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante',
    score: 1,
    user_id: 3,
    reviewee_id: 2,
  },
  {
    text: 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero',
    score: 1,
    user_id: 4,
    reviewee_id: 1,
  },
  {
    text: 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit',
    score: 4,
    user_id: 4,
    reviewee_id: 6,
  },
  {
    text: 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae',
    score: 2,
    user_id: 3,
    reviewee_id: 6,
  },
  {
    text: 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin',
    score: 4,
    user_id: 1,
    reviewee_id: 5,
  },
  {
    text: 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer',
    score: 2,
    user_id: 4,
    reviewee_id: 4,
  },
  {
    text: 'tristique est et tempus semper est quam pharetra magna ac consequat metus',
    score: 2,
    user_id: 4,
    reviewee_id: 1,
  },
  {
    text: 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque',
    score: 5,
    user_id: 2,
    reviewee_id: 3,
  },
  {
    text: 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla',
    score: 4,
    user_id: 6,
    reviewee_id: 1,
  },
  {
    text: 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed',
    score: 3,
    user_id: 6,
    reviewee_id: 2,
  },
  {
    text: 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean',
    score: 1,
    user_id: 2,
    reviewee_id: 2,
  },
  {
    text: 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum',
    score: 3,
    user_id: 6,
    reviewee_id: 2,
  },
  {
    text: 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in',
    score: 5,
    user_id: 4,
    reviewee_id: 2,
  },
  {
    text: 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum',
    score: 4,
    user_id: 4,
    reviewee_id: 3,
  },
  {
    text: 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum',
    score: 4,
    user_id: 4,
    reviewee_id: 3,
  },
  {
    text: 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a',
    score: 2,
    user_id: 3,
    reviewee_id: 1,
  },
  {
    text: 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat',
    score: 4,
    user_id: 2,
    reviewee_id: 3,
  },
  {
    text: 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam',
    score: 4,
    user_id: 5,
    reviewee_id: 6,
  },
  {
    text: 'mi sit amet lobortis sapien sapien non mi integer ac neque duis',
    score: 3,
    user_id: 4,
    reviewee_id: 3,
  },
  {
    text: 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut',
    score: 4,
    user_id: 4,
    reviewee_id: 4,
  },
  {
    text: 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet',
    score: 3,
    user_id: 5,
    reviewee_id: 4,
  },
  {
    text: 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat',
    score: 5,
    user_id: 4,
    reviewee_id: 1,
  },
  {
    text: 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus',
    score: 2,
    user_id: 2,
    reviewee_id: 5,
  },
];

const seedReview = () => Review.bulkCreate(reviewData);

module.exports = seedReview;
